<a href="https://colab.research.google.com/github/EmmanuelECCI/Logic-Gate-AI/blob/main/Sklearn_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #procesamiento numerico


In [2]:
X = [
	[0, 0],
	[0, 1],
	[1, 0],
  [1, 1]
]
X_np = np.array(X)

print(X_np)
print()
Y= [
    [0],
    [1],
    [1],
    [0]
]
Y_np = np.array(Y)
print(Y_np)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]

[[0]
 [1]
 [1]
 [0]]


In [4]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

#X, Y = make_classification(n_samples=4, random_state=1)
#X_train, X_test, y_train, y_test = train_test_split(X_np, Y_np, stratify=Y_np,random_state=1)
clf = MLPClassifier(hidden_layer_sizes=3,learning_rate_init=0.01, max_iter=50,activation='logistic',solver='lbfgs')#Creando red neuronal
clf.fit(X_np, Y_np)# HAciendo entrenamiento
clf.predict(Y_np)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 0])